#!/bin/bash
#
# USAGE: gmvn <parameters and goals>
# 
# Invoke maven with the supplied parameters and goals.
# 
# When the build is complete, send a message to growl indicating if the build was successful, and
# the directory in which it was run (in case there are multiple builds running concurrently).
#

# Print the header comment from this file, ducking the shebang line, and stopping a the first line that doesn't start with a hash
function print_header_comment {
        awk '/^# / { print substr( $0, 3 ) }; $0 !~ /^#/ { exit }' $0
}

# Send a success or failure notification
function notify {
	local PROJECT=${PWD##*/}
	if [ $1 ]; then
		echo "Build '$PROJECT' completed successfully." | growlnotify "Maven" --name maven --image ~/scripts/resources/maven-growl-success.jpg > /dev/null 2>&1
	else
		echo "Build '$PROJECT' failed!" | growlnotify "Maven" --name maven --image ~/scripts/resources/maven-growl-failure.jpg > /dev/null 2>&1		
	fi
}

# Print Usage or Execute
if [ $# == 0 ]; then
  print_header_comment
else
	mvn $*
	notify $?
fi
